series:
  720_Group:
    - 800 Words
    - Adventure Time
    - Aquarius US
    - The 100
    - Banchee
    - Constantine
    - Continuum
    - The Walking Dead
    - Dark Matter
    - Doctor Who 2005
    - Fear The Walking Dead
    - Mr Robot
    - The Librarians
    - Scorpion
    - The Simpsons
    - The Big Bang Theory
    - Game of Thrones
    - Arrow
    - Dig
    - The Last Man on Earth
    - The Flash
    - Silicon Valley
    - iZombie
    - Man Finds Food
    - The Messengers
    - Marvel's Agents of S.H.I.E.L.D.
    - Stitchers
    - Killjoys
    - Falling Skies
    - Limitless
  480_Group:
    - Bering Sea Gold
    - Man Vs Food
    - 12 Monkeys
    - A Cook Abroad
    - Almost Human
    - American Dad!
    - Atlantis
    - Awkward
    - Battle Creek
    - Back in time for dinner
    - Boardwalk Empire
    - Bones
    - Better Call Saul
    - Covert Affairs
    - Criminal Minds
    - Castle 2009
    - Chicago PD
    - Da Vinci's Demons
    - Defiance
    - Doctor Foster
    - Dominion
    - Dracula
    - Elementary
    - Family Guy
    - Fortitude
    - Garage Squad
    - Gotham
    - It's Always Sunny in…
    - Masters of Sex
    - New Girl
    - Orphan Black
    - Outlander
    - Penny Dreadful
    - Ray Donovan
    - Resurrection
    - Revenge
    - Revolution
    - Rookie Blue
    - Scream Queens
    - Sherlock
    - Significant Mother
    - Sleepy Hollow
    - Sons of Anarchy
    - The Astronaut Wives Club
    - The Blacklist
    - The Leftovers
    - The Listener
    - The Odd Couple
    - The Originals
    - Top Gear
    - The Slap (US)
    - Under The Dome
    - Wayward Pines
    - Wheeler Dealers
    - The Millers
    - Younger
    - Vikings